import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { AppText as Text } from '@/components/app/Typography';
import { AppShell } from '@/components/app/AppShell';
import { ErrorState, LoadingState } from '@/components/app/ScreenState';
import { Avatar } from '@/components/community/Avatar';
import { getUserProfile, requestFriend } from '@/features/settings/settingsService';
import type { PublicProfile } from '@/features/settings/types';
import { useLanguage } from '@/features/localization/LanguageProvider';
import { layout } from '@/theme/layout';
import { Toast, type ToastMessage } from '@/components/app/Toast';

export default function PublicProfileScreen() {
  const params = useLocalSearchParams<{ userId: string }>(); const userId = Number(params.userId);
  const { language } = useLanguage(); const pt = language === 'pt';
  const [profile, setProfile] = useState<PublicProfile | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [toast, setToast] = useState<ToastMessage | null>(null);
  useEffect(() => { if (Number.isFinite(userId)) getUserProfile(userId).then(setProfile).catch((failure) => setError(failure instanceof Error ? failure.message : pt ? 'Não foi possível carregar o perfil.' : 'Unable to load profile.')); }, [pt, userId]);
  async function addFriend() { if (!profile || !['NONE', 'PENDING_INCOMING'].includes(profile.friendshipStatus ?? '')) return; const accepting = profile.friendshipStatus === 'PENDING_INCOMING'; setBusy(true); try { await requestFriend(profile.userId); setProfile({ ...profile, friendshipStatus: accepting ? 'FRIENDS' : 'PENDING_OUTGOING' }); setToast({ id: Date.now(), tone: 'success', text: accepting ? (pt ? 'Pedido aceite.' : 'Request accepted.') : (pt ? 'Pedido enviado.' : 'Request sent.') }); } catch (failure) { setToast({ id: Date.now(), tone: 'error', text: failure instanceof Error ? failure.message : pt ? 'Não foi possível enviar o pedido.' : 'Unable to send request.' }); } finally { setBusy(false); } }
  const countryNames: Record<string, string> = { MZ: pt ? 'Moçambique' : 'Mozambique', BR: 'Brasil', PT: 'Portugal', AO: 'Angola', US: pt ? 'Estados Unidos' : 'United States' };
  const place = profile ? [profile.location, profile.countryCode ? countryNames[profile.countryCode] ?? profile.countryCode : null].filter(Boolean).join(', ') : '';
  const joined = profile ? new Intl.DateTimeFormat(pt ? 'pt' : 'en', { month: 'long', year: 'numeric' }).format(new Date(profile.joinedAt)) : '';
  return <AppShell active="community"><ScrollView contentContainerStyle={styles.screen}>
    <Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={23} color="#536071" /></Pressable>
    {!profile && !error ? <LoadingState label={pt ? 'A carregar perfil…' : 'Loading profile…'} /> : null}{error ? <ErrorState message={error} onRetry={() => getUserProfile(userId).then(setProfile)} /> : null}
    {profile ? <><View style={styles.hero}><Avatar name={profile.fullname} uri={profile.profilePictureUrl} size={82} /><Text style={styles.name}>{profile.fullname}</Text><Text style={styles.username}>@{profile.username}</Text></View>
      <View style={styles.stats}><View style={styles.stat}><Text style={styles.statNumber}>{profile.postsCount}</Text><Text style={styles.statLabel}>{pt ? 'Publicações' : 'Posts'}</Text></View><View style={styles.separator} /><View style={styles.stat}><Text style={styles.statNumber}>{profile.friendsCount}</Text><Text style={styles.statLabel}>{pt ? 'Amigos' : 'Friends'}</Text></View></View>
      <View style={styles.details}>
        <View style={styles.detailRow}><View style={styles.detailIcon}><Ionicons name="chatbox-ellipses-outline" size={17} color="#a86608" /></View><View style={styles.detailCopy}><Text style={styles.detailLabel}>{pt ? 'Sobre' : 'About'}</Text><Text style={styles.detailText}>{profile.bio?.trim() || (pt ? 'Este utilizador ainda não adicionou uma biografia.' : 'This user has not added a bio yet.')}</Text></View></View>
        <View style={styles.detailRow}><View style={styles.detailIcon}><Ionicons name="location-outline" size={18} color="#a86608" /></View><View style={styles.detailCopy}><Text style={styles.detailLabel}>{pt ? 'Localização' : 'Location'}</Text><Text style={styles.detailText}>{place || (pt ? 'Não indicada' : 'Not shared')}</Text></View></View>
        <View style={[styles.detailRow, styles.lastDetail]}><View style={styles.detailIcon}><Ionicons name="calendar-outline" size={18} color="#a86608" /></View><View style={styles.detailCopy}><Text style={styles.detailLabel}>{pt ? 'Membro desde' : 'Member since'}</Text><Text style={styles.detailText}>{joined}</Text></View></View>
      </View>
      {profile.friendshipStatus !== 'SELF' ? <Pressable disabled={busy || !['NONE', 'PENDING_INCOMING'].includes(profile.friendshipStatus ?? '')} onPress={addFriend} style={[styles.button, !['NONE', 'PENDING_INCOMING'].includes(profile.friendshipStatus ?? '') && styles.secondary]}><Ionicons name={profile.friendshipStatus === 'FRIENDS' ? 'checkmark-circle-outline' : 'person-add-outline'} size={19} color={['NONE', 'PENDING_INCOMING'].includes(profile.friendshipStatus ?? '') ? '#fff' : '#c77600'} /><Text style={[styles.buttonText, !['NONE', 'PENDING_INCOMING'].includes(profile.friendshipStatus ?? '') && styles.secondaryText]}>{profile.friendshipStatus === 'FRIENDS' ? (pt ? 'Amigos' : 'Friends') : profile.friendshipStatus === 'PENDING_OUTGOING' ? (pt ? 'Pedido enviado' : 'Request sent') : profile.friendshipStatus === 'PENDING_INCOMING' ? (pt ? 'Aceitar pedido' : 'Accept request') : (pt ? 'Adicionar amigo' : 'Add friend')}</Text></Pressable> : null}
      {profile.friendshipStatus !== 'SELF' ? <Pressable disabled={profile.friendshipStatus !== 'FRIENDS'} onPress={() => router.push({ pathname: '/chat/[friendId]', params: { friendId: String(profile.userId) } })} style={[styles.messageButton, profile.friendshipStatus !== 'FRIENDS' && styles.messageDisabled]}><Ionicons name={profile.friendshipStatus === 'FRIENDS' ? 'chatbubble-outline' : 'lock-closed-outline'} size={19} color={profile.friendshipStatus === 'FRIENDS' ? '#374354' : '#a4abb3'} /><View style={styles.messageCopy}><Text style={styles.messageTitle}>{pt ? `Conversar com @${profile.username}` : `Message @${profile.username}`}</Text>{profile.friendshipStatus !== 'FRIENDS' ? <Text style={styles.messageHint}>{pt ? 'Fica disponível quando forem amigos.' : 'Available once you become friends.'}</Text> : null}</View><Ionicons name="chevron-forward" size={19} color="#8b949f" /></Pressable> : null}
    </> : null}
  </ScrollView><Toast message={toast} onDismiss={() => setToast(null)} /></AppShell>;
}
const styles = StyleSheet.create({ screen: { padding: layout.screenPadding, paddingBottom: 30 }, back: { width: 40, height: 40, justifyContent: 'center' }, hero: { alignItems: 'center', paddingTop: 12 }, name: { marginTop: 13, color: '#151c24', fontSize: 23, fontWeight: '800' }, username: { marginTop: 3, color: '#7b8491', fontSize: 13 }, stats: { marginTop: 24, paddingVertical: 15, borderWidth: 1, borderColor: '#e4e7ea', borderRadius: 14, flexDirection: 'row', backgroundColor: '#fff' }, stat: { flex: 1, alignItems: 'center' }, statNumber: { color: '#17202a', fontSize: 20, fontWeight: '800' }, statLabel: { marginTop: 3, color: '#7a8490', fontSize: 11 }, separator: { width: 1, backgroundColor: '#e4e7ea' }, details: { marginTop: 12, overflow: 'hidden', borderWidth: 1, borderColor: '#e4e7ea', borderRadius: 14, backgroundColor: '#fff' }, detailRow: { padding: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#e4e7ea', flexDirection: 'row', alignItems: 'flex-start', gap: 11 }, lastDetail: { borderBottomWidth: 0 }, detailIcon: { width: 34, height: 34, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff5e8' }, detailCopy: { flex: 1 }, detailLabel: { color: '#697586', fontSize: 11, fontWeight: '700' }, detailText: { marginTop: 3, color: '#27313c', fontSize: 13, lineHeight: 20 }, button: { height: 48, marginTop: 12, borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: '#e9900c' }, secondary: { borderWidth: 1, borderColor: '#efd7b4', backgroundColor: '#fff8ed' }, buttonText: { color: '#fff', fontSize: 14, fontWeight: '700' }, secondaryText: { color: '#c77600' }, messageButton: { minHeight: 58, marginTop: 10, paddingHorizontal: 14, borderWidth: 1, borderColor: '#e4e7ea', borderRadius: 12, flexDirection: 'row', alignItems: 'center', gap: 11, backgroundColor: '#fff' }, messageDisabled: { backgroundColor: '#f7f7f7' }, messageCopy: { flex: 1 }, messageTitle: { color: '#374354', fontSize: 13, fontWeight: '700' }, messageHint: { marginTop: 2, color: '#8b949f', fontSize: 10 } });
