import { MaterialCommunityIcons } from '@expo/vector-icons';
import * as Clipboard from 'expo-clipboard';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, Share, StyleSheet, View } from 'react-native';
import { AppText as Text, AppTextInput as TextInput } from '@/components/app/Typography';

import { Avatar } from '@/components/community/Avatar';
import { SettingsScreen, settingsStyles } from '@/components/settings/SettingsUI';
import { cancelFriendRequest, getFriends, getPublicProfileByFriendCode, getSettings, requestFriend } from '@/features/settings/settingsService';
import type { FriendshipListItem, PublicProfile } from '@/features/settings/types';
import { useLanguage } from '@/features/localization/LanguageProvider';
import { Toast, type ToastMessage } from '@/components/app/Toast';
import { router } from 'expo-router';

type ViewMode = 'find' | 'mine';
export default function AddFriendsScreen() {
  const { language } = useLanguage(); const pt = language === 'pt';
  const [mode, setMode] = useState<ViewMode>('find'); const [friendCode, setFriendCode] = useState(''); const [myFriendCode, setMyFriendCode] = useState('');
  const [profile, setProfile] = useState<PublicProfile | null>(null); const [loading, setLoading] = useState(false);
  const [toast, setToast] = useState<ToastMessage | null>(null);
  const [friends, setFriends] = useState<FriendshipListItem[]>([]);
  useEffect(() => { Promise.all([getSettings(), getFriends()]).then(([value, currentFriends]) => { setMyFriendCode(value.friendCode); setFriends(currentFriends); }).catch((failure) => setToast({ id: Date.now(), tone: 'error', text: failure instanceof Error ? failure.message : pt ? 'Não foi possível carregar os seus dados.' : 'Unable to load your information.' })); }, [pt]);
  async function find() {
    const normalized = friendCode.replace(/[^A-Z0-9]/g, '');
    const ownCode = myFriendCode.replace(/[^A-Z0-9]/g, '');
    if (normalized.length !== 8) return;
    if (ownCode && normalized === ownCode) {
      setProfile(null);
      setToast({ id: Date.now(), tone: 'error', text: pt ? 'Não pode adicionar o seu próprio código.' : 'You cannot add your own friend code.' });
      return;
    }
    setLoading(true); setProfile(null);
    try { setProfile(await getPublicProfileByFriendCode(friendCode)); }
    catch (failure) {
      const message = failure instanceof Error ? failure.message : '';
      const ownCodeError = /own friend code|yourself/i.test(message);
      setToast({ id: Date.now(), tone: 'error', text: ownCodeError ? (pt ? 'Não pode adicionar o seu próprio código.' : 'You cannot add your own friend code.') : message || (pt ? 'Código de amigo não encontrado.' : 'Friend code not found.') });
    }
    finally { setLoading(false); }
  }
  async function add() { if (!profile || !['NONE', 'PENDING_INCOMING'].includes(profile.friendshipStatus ?? '')) return; const accepting = profile.friendshipStatus === 'PENDING_INCOMING'; setLoading(true); try { const result = await requestFriend(profile.userId); setProfile({ ...profile, friendshipId: result.friendshipId, friendshipStatus: accepting ? 'FRIENDS' : 'PENDING_OUTGOING' }); setToast({ id: Date.now(), tone: 'success', text: accepting ? (pt ? 'Pedido aceite.' : 'Friend request accepted.') : (pt ? 'Pedido de amizade enviado.' : 'Friend request sent.') }); } catch (failure) { setToast({ id: Date.now(), tone: 'error', text: failure instanceof Error ? failure.message : pt ? 'Não foi possível enviar o pedido.' : 'Could not add this friend.' }); } finally { setLoading(false); } }
  async function cancelRequest() { if (!profile?.friendshipId || profile.friendshipStatus !== 'PENDING_OUTGOING') return; setLoading(true); try { await cancelFriendRequest(profile.friendshipId); setProfile({ ...profile, friendshipId: null, friendshipStatus: 'NONE' }); setToast({ id: Date.now(), tone: 'success', text: pt ? 'Pedido de amizade cancelado.' : 'Friend request cancelled.' }); } catch (failure) { setToast({ id: Date.now(), tone: 'error', text: failure instanceof Error ? failure.message : pt ? 'Não foi possível cancelar o pedido.' : 'Unable to cancel the request.' }); } finally { setLoading(false); } }
  const shareCode = myFriendCode || '---- ----';
  return <SettingsScreen title={pt ? 'Adicionar amigos' : 'Add Friends'} subtitle={pt ? 'Encontre e conecte-se com os seus amigos.' : 'Find and connect with your friends.'}>
    <View style={styles.tabs}><Pressable onPress={() => setMode('find')} style={[styles.tab, mode === 'find' && styles.activeTab]}><Text style={[styles.tabText, mode === 'find' && styles.activeText]}>{pt ? 'Adicionar por código' : 'Add by Code'}</Text></Pressable><Pressable onPress={() => setMode('mine')} style={[styles.tab, mode === 'mine' && styles.activeTab]}><Text style={[styles.tabText, mode === 'mine' && styles.activeText]}>{pt ? 'Meu código' : 'My Code'}</Text></Pressable></View>
    {mode === 'mine' ? <View style={styles.codeCard}><Text style={styles.codeLabel}>{pt ? 'Seu código privado Koino' : 'Your Private Koino Code'}</Text><Text style={styles.code}>{shareCode}</Text><View style={styles.codeActions}><Pressable disabled={!myFriendCode} onPress={async () => { await Clipboard.setStringAsync(shareCode); setToast({ id: Date.now(), tone: 'success', text: pt ? 'Código copiado.' : 'Code copied.' }); }} style={[styles.codeButton, !myFriendCode && styles.disabled]}><MaterialCommunityIcons name="content-copy" size={21} color="#303b49" /><Text style={styles.codeButtonText}>{pt ? 'Copiar código' : 'Copy Code'}</Text></Pressable><Pressable disabled={!myFriendCode} onPress={() => Share.share({ message: pt ? `Adicione-me no Koino com o meu código privado: ${shareCode}` : `Add me on Koino with my private friend code: ${shareCode}` })} style={[styles.codeButton, !myFriendCode && styles.disabled]}><MaterialCommunityIcons name="share-variant-outline" size={21} color="#303b49" /><Text style={styles.codeButtonText}>{pt ? 'Partilhar' : 'Share Code'}</Text></Pressable></View><Text style={styles.shareHint}>{pt ? 'Partilhe este código apenas com pessoas de confiança.' : 'Only share this private code with people you trust.'}</Text></View> : null}
    {mode === 'find' && !profile ? <View style={styles.findArea}><View style={styles.friendIcon}><MaterialCommunityIcons name="account-key-outline" size={31} color="#ed9210" /></View><Text style={styles.findTitle}>{pt ? 'Insira o código de um amigo' : 'Enter a friend’s code'}</Text><Text style={styles.findHint}>{pt ? 'Peça o código privado ao seu amigo e insira-o abaixo.' : 'Ask your friend for their private Koino code and enter it below.'}</Text><TextInput value={friendCode} onChangeText={(value) => { setFriendCode(value.toUpperCase().replace(/[^A-Z0-9-]/g, '').slice(0, 9)); setProfile(null); }} onSubmitEditing={find} autoCapitalize="characters" maxLength={9} placeholder="AB12-CD34" placeholderTextColor="#949ca7" style={settingsStyles.field} /><Pressable disabled={loading || friendCode.replace(/[^A-Z0-9]/g, '').length !== 8} onPress={find} style={[settingsStyles.primary, (loading || friendCode.replace(/[^A-Z0-9]/g, '').length !== 8) && styles.disabled]}>{loading ? <ActivityIndicator color="#fff" /> : <Text style={settingsStyles.primaryText}>{pt ? 'Encontrar amigo' : 'Find Friend'}</Text>}</Pressable></View> : null}
    {mode === 'find' && profile ? <View style={styles.result}><Avatar name={profile.fullname} uri={profile.profilePictureUrl} size={76} /><Text style={styles.resultName}>{profile.fullname}</Text><Text style={styles.handle}>@{profile.username}</Text>{profile.bio ? <Text style={styles.bio}>{profile.bio}</Text> : null}<Pressable disabled={loading || !['NONE', 'PENDING_INCOMING'].includes(profile.friendshipStatus ?? '')} onPress={add} style={[settingsStyles.primary, styles.resultButton, (loading || !['NONE', 'PENDING_INCOMING'].includes(profile.friendshipStatus ?? '')) && styles.disabledButton]}>{loading ? <ActivityIndicator color="#fff" /> : <><MaterialCommunityIcons name={profile.friendshipStatus === 'FRIENDS' ? 'account-check-outline' : profile.friendshipStatus === 'PENDING_OUTGOING' ? 'send-check-outline' : 'account-plus-outline'} size={19} color={['NONE', 'PENDING_INCOMING'].includes(profile.friendshipStatus ?? '') ? '#fff' : '#87909b'} /><Text style={[settingsStyles.primaryText, !['NONE', 'PENDING_INCOMING'].includes(profile.friendshipStatus ?? '') && styles.disabledText]}>{profile.friendshipStatus === 'FRIENDS' ? (pt ? 'Já são amigos' : 'Already Friends') : profile.friendshipStatus === 'PENDING_INCOMING' ? (pt ? 'Aceitar pedido' : 'Accept Request') : profile.friendshipStatus === 'PENDING_OUTGOING' ? (pt ? 'Pedido enviado' : 'Request Sent') : profile.friendshipStatus === 'SELF' ? (pt ? 'Este é o seu perfil' : 'This is your profile') : (pt ? 'Adicionar amigo' : 'Add Friend')}</Text></>}</Pressable>{profile.friendshipStatus === 'PENDING_OUTGOING' ? <Pressable disabled={loading} onPress={cancelRequest} style={styles.cancelRequest}><MaterialCommunityIcons name="close-circle-outline" size={18} color="#a0473f" /><Text style={styles.cancelRequestText}>{pt ? 'Cancelar pedido' : 'Cancel request'}</Text></Pressable> : null}<Pressable onPress={() => { setProfile(null); setFriendCode(''); }}><Text style={styles.cancel}>{pt ? 'Voltar' : 'Back'}</Text></Pressable></View> : null}
    <View style={styles.friendsSection}><Text style={styles.friendsTitle}>{pt ? `Os seus amigos (${friends.length})` : `Your friends (${friends.length})`}</Text>{friends.length ? friends.map((item) => <Pressable key={item.friendshipId} onPress={() => router.push({ pathname: '/profile/[userId]', params: { userId: String(item.user.userId) } })} style={styles.friendRow}><Avatar name={item.user.fullname} uri={item.user.profilePictureUrl} size={43} /><View style={styles.friendInfo}><Text style={styles.friendName}>{item.user.fullname}</Text><Text style={styles.friendHandle}>@{item.user.username}</Text></View><MaterialCommunityIcons name="chevron-right" size={21} color="#7d8793" /></Pressable>) : <Text style={styles.noFriends}>{pt ? 'Os amigos ativos aparecerão aqui.' : 'Your active friends will appear here.'}</Text>}</View>
    <Toast message={toast} duration={3500} onDismiss={() => setToast(null)} />
  </SettingsScreen>;
}
const styles = StyleSheet.create({
  friendsSection: { marginTop: 22, paddingTop: 18, borderTopWidth: 1, borderTopColor: '#e7e9ec' }, friendsTitle: { marginBottom: 8, color: '#172029', fontSize: 16, fontWeight: '700' }, friendRow: { minHeight: 66, paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: '#edf0f2', flexDirection: 'row', alignItems: 'center' }, friendInfo: { flex: 1, marginLeft: 11 }, friendName: { color: '#1b242d', fontSize: 14, fontWeight: '700' }, friendHandle: { marginTop: 2, color: '#7b8491', fontSize: 11 }, noFriends: { paddingVertical: 18, color: '#7b8491', fontSize: 12, textAlign: 'center' },
  tabs: { height: 48, padding: 3, borderRadius: 10, flexDirection: 'row', backgroundColor: '#f6f6f7' }, tab: { flex: 1, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, activeTab: { borderWidth: 1, borderColor: '#efb464', backgroundColor: '#fff' }, tabText: { color: '#697486', fontSize: 13, fontWeight: '600' }, activeText: { color: '#d97e00' },
  findArea: { gap: 12, paddingTop: 6 }, friendIcon: { width: 64, height: 64, marginBottom: 2, borderRadius: 20, alignSelf: 'center', alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff5e8' }, findTitle: { color: '#161e27', fontSize: 20, fontWeight: '700', textAlign: 'center' }, findHint: { marginBottom: 5, paddingHorizontal: 14, color: '#778191', fontSize: 13, lineHeight: 20, textAlign: 'center' },
  codeCard: { minHeight: 285, padding: 24, borderWidth: 1, borderColor: '#efcc99', borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fffaf2' }, codeLabel: { color: '#242d36', fontSize: 13, fontWeight: '600' }, code: { marginTop: 11, color: '#111820', fontSize: 31, fontWeight: '700' }, codeActions: { marginTop: 25, flexDirection: 'row', gap: 16 }, codeButton: { width: 106, minHeight: 68, borderWidth: 1, borderColor: '#dfe3e8', borderRadius: 10, alignItems: 'center', justifyContent: 'center', gap: 5, backgroundColor: '#fff' }, codeButtonText: { color: '#303944', fontSize: 11, fontWeight: '600' }, shareHint: { marginTop: 26, color: '#76808d', fontSize: 12, lineHeight: 18, textAlign: 'center' },
  result: { gap: 10, alignItems: 'center' }, resultName: { color: '#131b24', fontSize: 22, fontWeight: '700' }, handle: { color: '#748090', fontSize: 13 }, bio: { maxWidth: 290, color: '#687485', fontSize: 13, lineHeight: 20, textAlign: 'center' }, resultButton: { width: '100%', marginTop: 6, flexDirection: 'row', gap: 8 }, disabledButton: { borderWidth: 1, borderColor: '#e0e3e7', backgroundColor: '#f4f5f6' }, disabledText: { color: '#87909b' }, cancelRequest: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, cancelRequestText: { color: '#a0473f', fontSize: 12, fontWeight: '700' }, cancel: { padding: 10, color: '#1e2730', fontSize: 13, fontWeight: '600' }, disabled: { opacity: 0.45 },
});
