import { MaterialCommunityIcons } from '@expo/vector-icons';
import * as Clipboard from 'expo-clipboard';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, Share, StyleSheet, Text, TextInput, View } from 'react-native';

import { Avatar } from '@/components/community/Avatar';
import { SettingsScreen, settingsStyles } from '@/components/settings/SettingsUI';
import { getPublicProfileByFriendCode, getSettings, requestFriend } from '@/features/settings/settingsService';
import type { PublicProfile } from '@/features/settings/types';

type ViewMode = 'find' | 'mine';
export default function AddFriendsScreen() {
  const [mode, setMode] = useState<ViewMode>('find'); const [friendCode, setFriendCode] = useState(''); const [myFriendCode, setMyFriendCode] = useState('');
  const [profile, setProfile] = useState<PublicProfile | null>(null); const [added, setAdded] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { getSettings().then((value) => setMyFriendCode(value.friendCode)).catch(() => {}); }, []);
  async function find() { if (!friendCode.trim()) return; setLoading(true); setError(''); setProfile(null); setAdded(false); try { setProfile(await getPublicProfileByFriendCode(friendCode)); } catch (failure) { setError(failure instanceof Error ? failure.message : 'Friend code not found.'); } finally { setLoading(false); } }
  async function add() { if (!profile) return; setLoading(true); try { await requestFriend(profile.userId); setAdded(true); } catch (failure) { setError(failure instanceof Error ? failure.message : 'Could not add this friend.'); } finally { setLoading(false); } }
  const shareCode = myFriendCode || '---- ----';
  return <SettingsScreen title="Add Friends" subtitle="Find and connect with your friends.">
    <View style={styles.tabs}><Pressable onPress={() => setMode('find')} style={[styles.tab, mode === 'find' && styles.activeTab]}><Text style={[styles.tabText, mode === 'find' && styles.activeText]}>Add by Code</Text></Pressable><Pressable onPress={() => setMode('mine')} style={[styles.tab, mode === 'mine' && styles.activeTab]}><Text style={[styles.tabText, mode === 'mine' && styles.activeText]}>My Code</Text></Pressable></View>
    {mode === 'mine' ? <View style={styles.codeCard}><Text style={styles.codeLabel}>Your Private Koino Code</Text><Text style={styles.code}>{shareCode}</Text><View style={styles.codeActions}><Pressable onPress={() => Clipboard.setStringAsync(shareCode)} style={styles.codeButton}><MaterialCommunityIcons name="content-copy" size={21} color="#303b49" /><Text style={styles.codeButtonText}>Copy Code</Text></Pressable><Pressable onPress={() => Share.share({ message: `Add me on Koino with my private friend code: ${shareCode}` })} style={styles.codeButton}><MaterialCommunityIcons name="share-variant-outline" size={21} color="#303b49" /><Text style={styles.codeButtonText}>Share Code</Text></Pressable></View><Text style={styles.shareHint}>Only share this private code with people you trust.</Text></View> : null}
    {mode === 'find' && !profile ? <View style={styles.findArea}><View style={styles.friendIcon}><MaterialCommunityIcons name="account-key-outline" size={47} color="#ed9210" /></View><Text style={styles.findTitle}>Enter a friend&apos;s code</Text><Text style={styles.findHint}>Ask your friend for their private Koino code and enter it below.</Text><TextInput value={friendCode} onChangeText={(value) => setFriendCode(value.toUpperCase().replace(/[^A-Z0-9-]/g, '').slice(0, 9))} onSubmitEditing={find} autoCapitalize="characters" maxLength={9} placeholder="AB12-CD34" placeholderTextColor="#949ca7" style={settingsStyles.field} /><Pressable disabled={loading || friendCode.replace(/[^A-Z0-9]/g, '').length !== 8} onPress={find} style={settingsStyles.primary}>{loading ? <ActivityIndicator color="#fff" /> : <Text style={settingsStyles.primaryText}>Find Friend</Text>}</Pressable></View> : null}
    {mode === 'find' && profile && !added ? <View style={styles.result}><Avatar name={profile.fullname} uri={profile.profilePictureUrl} size={82} /><Text style={styles.resultName}>{profile.fullname}</Text><Text style={styles.handle}>@{profile.username}</Text>{profile.bio ? <Text style={styles.bio}>{profile.bio}</Text> : null}<Pressable disabled={loading || profile.friendshipStatus === 'ACCEPTED'} onPress={add} style={settingsStyles.primary}>{loading ? <ActivityIndicator color="#fff" /> : <Text style={settingsStyles.primaryText}>{profile.friendshipStatus === 'ACCEPTED' ? 'Already Friends' : profile.friendshipStatus === 'PENDING' ? 'Request Pending' : 'Add Friend'}</Text>}</Pressable><Pressable onPress={() => setProfile(null)}><Text style={styles.cancel}>Cancel</Text></Pressable></View> : null}
    {mode === 'find' && added ? <View style={styles.result}><View style={styles.success}><MaterialCommunityIcons name="check" size={42} color="#fff" /></View><Text style={styles.resultName}>Friend request sent!</Text><Text style={styles.bio}>{profile?.fullname} will receive your request.</Text><Pressable onPress={() => router.push('/chat')} style={settingsStyles.primary}><Text style={settingsStyles.primaryText}>Open Chat</Text></Pressable><Pressable onPress={() => { setProfile(null); setAdded(false); setFriendCode(''); }}><Text style={styles.cancel}>Find another friend</Text></Pressable></View> : null}
    {error ? <Text style={settingsStyles.status}>{error}</Text> : null}
  </SettingsScreen>;
}
const styles = StyleSheet.create({
  tabs: { height: 46, padding: 3, borderRadius: 8, flexDirection: 'row', backgroundColor: '#f6f6f7' }, tab: { flex: 1, borderRadius: 7, alignItems: 'center', justifyContent: 'center' }, activeTab: { borderWidth: 1, borderColor: '#efb464', backgroundColor: '#fff' }, tabText: { color: '#697486', fontSize: 10, fontWeight: '600' }, activeText: { color: '#d97e00' },
  findArea: { gap: 13 }, friendIcon: { width: 105, height: 105, marginBottom: 15, borderRadius: 53, alignSelf: 'center', alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff5e8' }, findTitle: { color: '#161e27', fontFamily: 'serif', fontSize: 19, fontWeight: '700', textAlign: 'center' }, findHint: { marginBottom: 10, color: '#778191', fontSize: 10, lineHeight: 16, textAlign: 'center' },
  codeCard: { minHeight: 285, padding: 24, borderWidth: 1, borderColor: '#efcc99', borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fffaf2' }, codeLabel: { color: '#242d36', fontSize: 11, fontWeight: '600' }, code: { marginTop: 11, color: '#111820', fontSize: 31, fontWeight: '700' }, codeActions: { marginTop: 25, flexDirection: 'row', gap: 20 }, codeButton: { width: 90, height: 61, borderWidth: 1, borderColor: '#dfe3e8', borderRadius: 8, alignItems: 'center', justifyContent: 'center', gap: 5, backgroundColor: '#fff' }, codeButtonText: { color: '#303944', fontSize: 9, fontWeight: '600' }, shareHint: { marginTop: 26, color: '#76808d', fontSize: 9 },
  result: { gap: 12, alignItems: 'center' }, resultName: { color: '#131b24', fontFamily: 'serif', fontSize: 21, fontWeight: '700' }, handle: { color: '#748090', fontSize: 11 }, bio: { maxWidth: 290, color: '#687485', fontSize: 10, lineHeight: 16, textAlign: 'center' }, cancel: { padding: 12, color: '#1e2730', fontSize: 11, fontWeight: '600' }, success: { width: 82, height: 82, borderRadius: 41, alignItems: 'center', justifyContent: 'center', backgroundColor: '#17b968', borderWidth: 10, borderColor: '#dff8e9' },
});
