import { MaterialCommunityIcons } from '@expo/vector-icons';
import * as Clipboard from 'expo-clipboard';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, Share, StyleSheet, View } from 'react-native';
import { AppText as Text, AppTextInput as TextInput } from '@/components/app/Typography';

import { Avatar } from '@/components/community/Avatar';
import { SettingsScreen, settingsStyles } from '@/components/settings/SettingsUI';
import { getPublicProfileByFriendCode, getSettings, requestFriend } from '@/features/settings/settingsService';
import type { PublicProfile } from '@/features/settings/types';
import { useLanguage } from '@/features/localization/LanguageProvider';
import { Toast, type ToastMessage } from '@/components/app/Toast';

type ViewMode = 'find' | 'mine';
export default function AddFriendsScreen() {
  const { language } = useLanguage(); const pt = language === 'pt';
  const [mode, setMode] = useState<ViewMode>('find'); const [friendCode, setFriendCode] = useState(''); const [myFriendCode, setMyFriendCode] = useState('');
  const [profile, setProfile] = useState<PublicProfile | null>(null); const [added, setAdded] = useState(false); const [loading, setLoading] = useState(false);
  const [toast, setToast] = useState<ToastMessage | null>(null);
  useEffect(() => { getSettings().then((value) => setMyFriendCode(value.friendCode)).catch((failure) => setToast({ id: Date.now(), tone: 'error', text: failure instanceof Error ? failure.message : pt ? 'Não foi possível carregar o seu código.' : 'Unable to load your code.' })); }, [pt]);
  async function find() { if (friendCode.replace(/[^A-Z0-9]/g, '').length !== 8) return; setLoading(true); setProfile(null); setAdded(false); try { setProfile(await getPublicProfileByFriendCode(friendCode)); } catch (failure) { setToast({ id: Date.now(), tone: 'error', text: failure instanceof Error ? failure.message : pt ? 'Código de amigo não encontrado.' : 'Friend code not found.' }); } finally { setLoading(false); } }
  async function add() { if (!profile || !['NONE', 'PENDING_INCOMING'].includes(profile.friendshipStatus ?? '')) return; const accepting = profile.friendshipStatus === 'PENDING_INCOMING'; setLoading(true); try { await requestFriend(profile.userId); setProfile({ ...profile, friendshipStatus: accepting ? 'FRIENDS' : 'PENDING_OUTGOING' }); setAdded(true); setToast({ id: Date.now(), tone: 'success', text: accepting ? (pt ? 'Pedido aceite.' : 'Friend request accepted.') : (pt ? 'Pedido de amizade enviado.' : 'Friend request sent.') }); } catch (failure) { setToast({ id: Date.now(), tone: 'error', text: failure instanceof Error ? failure.message : pt ? 'Não foi possível enviar o pedido.' : 'Could not add this friend.' }); } finally { setLoading(false); } }
  const shareCode = myFriendCode || '---- ----';
  return <SettingsScreen title={pt ? 'Adicionar amigos' : 'Add Friends'} subtitle={pt ? 'Encontre e conecte-se com os seus amigos.' : 'Find and connect with your friends.'}>
    <View style={styles.tabs}><Pressable onPress={() => setMode('find')} style={[styles.tab, mode === 'find' && styles.activeTab]}><Text style={[styles.tabText, mode === 'find' && styles.activeText]}>{pt ? 'Adicionar por código' : 'Add by Code'}</Text></Pressable><Pressable onPress={() => setMode('mine')} style={[styles.tab, mode === 'mine' && styles.activeTab]}><Text style={[styles.tabText, mode === 'mine' && styles.activeText]}>{pt ? 'Meu código' : 'My Code'}</Text></Pressable></View>
    {mode === 'mine' ? <View style={styles.codeCard}><Text style={styles.codeLabel}>{pt ? 'Seu código privado Koino' : 'Your Private Koino Code'}</Text><Text style={styles.code}>{shareCode}</Text><View style={styles.codeActions}><Pressable disabled={!myFriendCode} onPress={async () => { await Clipboard.setStringAsync(shareCode); setToast({ id: Date.now(), tone: 'success', text: pt ? 'Código copiado.' : 'Code copied.' }); }} style={[styles.codeButton, !myFriendCode && styles.disabled]}><MaterialCommunityIcons name="content-copy" size={21} color="#303b49" /><Text style={styles.codeButtonText}>{pt ? 'Copiar código' : 'Copy Code'}</Text></Pressable><Pressable disabled={!myFriendCode} onPress={() => Share.share({ message: pt ? `Adicione-me no Koino com o meu código privado: ${shareCode}` : `Add me on Koino with my private friend code: ${shareCode}` })} style={[styles.codeButton, !myFriendCode && styles.disabled]}><MaterialCommunityIcons name="share-variant-outline" size={21} color="#303b49" /><Text style={styles.codeButtonText}>{pt ? 'Partilhar' : 'Share Code'}</Text></Pressable></View><Text style={styles.shareHint}>{pt ? 'Partilhe este código apenas com pessoas de confiança.' : 'Only share this private code with people you trust.'}</Text></View> : null}
    {mode === 'find' && !profile ? <View style={styles.findArea}><View style={styles.friendIcon}><MaterialCommunityIcons name="account-key-outline" size={47} color="#ed9210" /></View><Text style={styles.findTitle}>{pt ? 'Insira o código de um amigo' : 'Enter a friend’s code'}</Text><Text style={styles.findHint}>{pt ? 'Peça o código privado ao seu amigo e insira-o abaixo.' : 'Ask your friend for their private Koino code and enter it below.'}</Text><TextInput value={friendCode} onChangeText={(value) => setFriendCode(value.toUpperCase().replace(/[^A-Z0-9-]/g, '').slice(0, 9))} onSubmitEditing={find} autoCapitalize="characters" maxLength={9} placeholder="AB12-CD34" placeholderTextColor="#949ca7" style={settingsStyles.field} /><Pressable disabled={loading || friendCode.replace(/[^A-Z0-9]/g, '').length !== 8} onPress={find} style={[settingsStyles.primary, (loading || friendCode.replace(/[^A-Z0-9]/g, '').length !== 8) && styles.disabled]}>{loading ? <ActivityIndicator color="#fff" /> : <Text style={settingsStyles.primaryText}>{pt ? 'Encontrar amigo' : 'Find Friend'}</Text>}</Pressable></View> : null}
    {mode === 'find' && profile && !added ? <View style={styles.result}><Avatar name={profile.fullname} uri={profile.profilePictureUrl} size={82} /><Text style={styles.resultName}>{profile.fullname}</Text><Text style={styles.handle}>@{profile.username}</Text>{profile.bio ? <Text style={styles.bio}>{profile.bio}</Text> : null}<Pressable disabled={loading || !['NONE', 'PENDING_INCOMING'].includes(profile.friendshipStatus ?? '')} onPress={add} style={[settingsStyles.primary, (loading || !['NONE', 'PENDING_INCOMING'].includes(profile.friendshipStatus ?? '')) && styles.disabled]}>{loading ? <ActivityIndicator color="#fff" /> : <Text style={settingsStyles.primaryText}>{profile.friendshipStatus === 'FRIENDS' ? (pt ? 'Já são amigos' : 'Already Friends') : profile.friendshipStatus === 'PENDING_INCOMING' ? (pt ? 'Aceitar pedido' : 'Accept Request') : profile.friendshipStatus === 'PENDING_OUTGOING' ? (pt ? 'Pedido pendente' : 'Request Pending') : profile.friendshipStatus === 'SELF' ? (pt ? 'Este é o seu perfil' : 'This is your profile') : (pt ? 'Adicionar amigo' : 'Add Friend')}</Text>}</Pressable><Pressable onPress={() => setProfile(null)}><Text style={styles.cancel}>{pt ? 'Cancelar' : 'Cancel'}</Text></Pressable></View> : null}
    {mode === 'find' && added ? <View style={styles.result}><View style={styles.success}><MaterialCommunityIcons name="check" size={42} color="#fff" /></View><Text style={styles.resultName}>{pt ? 'Pedido enviado!' : 'Friend request sent!'}</Text><Text style={styles.bio}>{pt ? `${profile?.fullname} receberá o seu pedido.` : `${profile?.fullname} will receive your request.`}</Text><Pressable onPress={() => { setProfile(null); setAdded(false); setFriendCode(''); }} style={settingsStyles.primary}><Text style={settingsStyles.primaryText}>{pt ? 'Concluir' : 'Done'}</Text></Pressable></View> : null}
    <Toast message={toast} onDismiss={() => setToast(null)} />
  </SettingsScreen>;
}
const styles = StyleSheet.create({
  tabs: { height: 48, padding: 3, borderRadius: 10, flexDirection: 'row', backgroundColor: '#f6f6f7' }, tab: { flex: 1, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, activeTab: { borderWidth: 1, borderColor: '#efb464', backgroundColor: '#fff' }, tabText: { color: '#697486', fontSize: 13, fontWeight: '600' }, activeText: { color: '#d97e00' },
  findArea: { gap: 15 }, friendIcon: { width: 100, height: 100, marginBottom: 10, borderRadius: 50, alignSelf: 'center', alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff5e8' }, findTitle: { color: '#161e27', fontSize: 21, fontWeight: '700', textAlign: 'center' }, findHint: { marginBottom: 8, color: '#778191', fontSize: 13, lineHeight: 20, textAlign: 'center' },
  codeCard: { minHeight: 285, padding: 24, borderWidth: 1, borderColor: '#efcc99', borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fffaf2' }, codeLabel: { color: '#242d36', fontSize: 13, fontWeight: '600' }, code: { marginTop: 11, color: '#111820', fontSize: 31, fontWeight: '700' }, codeActions: { marginTop: 25, flexDirection: 'row', gap: 16 }, codeButton: { width: 106, minHeight: 68, borderWidth: 1, borderColor: '#dfe3e8', borderRadius: 10, alignItems: 'center', justifyContent: 'center', gap: 5, backgroundColor: '#fff' }, codeButtonText: { color: '#303944', fontSize: 11, fontWeight: '600' }, shareHint: { marginTop: 26, color: '#76808d', fontSize: 12, lineHeight: 18, textAlign: 'center' },
  result: { gap: 12, alignItems: 'center' }, resultName: { color: '#131b24', fontSize: 22, fontWeight: '700' }, handle: { color: '#748090', fontSize: 13 }, bio: { maxWidth: 290, color: '#687485', fontSize: 13, lineHeight: 20, textAlign: 'center' }, cancel: { padding: 12, color: '#1e2730', fontSize: 13, fontWeight: '600' }, success: { width: 82, height: 82, borderRadius: 41, alignItems: 'center', justifyContent: 'center', backgroundColor: '#17b968', borderWidth: 10, borderColor: '#dff8e9' }, disabled: { opacity: 0.45 },
});
